### ISSUE TITLE
Card rulings do not show when logged in

### ISSUE THREAD

**Issue by DoubleAitch** [Alsciende/fiveringsdb-ui#1]
Visiting a card page whilst logged in does not show any rulings.  Logging out then refreshing the page causes the rulings to appear.  Logging back in then refreshing and the rulings disappear.
Tested in Chrome v61.

Not Logged In:
![image](https://user-images.githubusercontent.com/7096796/31320539-177234f2-ac6e-11e7-95cd-127f9acafbbf.png)

Logged In:
![image](https://user-images.githubusercontent.com/7096796/31320550-45d1d47e-ac6e-11e7-897f-0da259ef1973.png)

**Comment by Alsciende** [comment]
Fixed. Thank you for the report!
