### ISSUE TITLE
Error when attempting to save a deck

### ISSUE THREAD

**Issue by DoubleAitch** [Alsciende/fiveringsdb-ui#2]
When attempting to save a deck I get a validation error.

> Error
> Validation Error for "data.description". This value should not be blank.

Tested on Chrome 61 and Safari.

![image](https://user-images.githubusercontent.com/7096796/31589159-b5a45638-b1f4-11e7-8840-ce369db79a95.png)

**Comment by Alsciende** [comment]
Thanks, fixed.
