### ISSUE TITLE
API for rules reference?

### ISSUE THREAD

**Issue by cielago** [Alsciende/fiveringsdb-ui#4]
it would be SUPER cool if https://fiveringsdb.com/rules/reference was accessible via an api, or even just rendered into xml or json or something like that that could be scraped by a bot. the l5r discord rules channels have made several requests for the ability to summon specific rules and we'd love to reference a single source.

**Comment by Alsciende** [comment]
I can't.

But it's permanent data. Why don't you just put it in the bot?

**Comment by Alsciende** [comment]
Actually, maybe I'll find a way in the future, because right now I'm not happy with how it works. But it works, so I won't touch it before quite a long time.
